const sections=[['bienvenue','Accueil'],['actualite',"* L’Actualité *"],['association',"L’Association"],['refuge','Le refuge et visite guidée'],['adopter','Nos Chats à Adopter'],['adoptes','Nos chats qui ont trouvé leur famille']];
const cats=window.CATS;const main=document.querySelector('main');const dialog=document.querySelector('dialog');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const age=c=>Number.isInteger(c.birth)?new Date().getFullYear()-c.birth:null;
const ageText=c=>age(c)===null?'Âge à préciser':age(c)===0?'Moins d’un an':`${age(c)} an${age(c)>1?'s':''}`;
const sex=c=>c.sex==='F'?'Femelle':c.sex==='M'?'Mâle':'Sexe à préciser';
function card(c){return `<button class="card" data-cat="${esc(c.id)}" aria-label="Voir la fiche de ${esc(c.name)}">${c.photos.length?`<img loading="lazy" src="${esc(c.photos[0])}" alt="${esc(c.name)}">`:'<div class="placeholder">Photo à venir</div>'}<div class="card-body"><span class="badge">${c.status==='adoptable'?'Cherche une famille':'A trouvé sa famille'}</span><h3>${esc(c.name)}</h3><div class="meta">${sex(c)} · ${ageText(c)}</div><div class="meta">${esc(c.color)}</div><div class="card-bottom"><span>Découvrir son histoire</span><span aria-hidden="true">↗</span></div></div></button>`}
function bindCards(){main.querySelectorAll('[data-cat]').forEach(el=>el.onclick=()=>showCat(el.dataset.cat))}
function showCat(id){const c=cats.find(c=>String(c.id)===id);if(!c)return;document.querySelector('#cat-detail').innerHTML=`<span class="eyebrow">${c.status==='adoptable'?'Une rencontre, une nouvelle vie':'Une famille trouvée'}</span><h2>${esc(c.name)}</h2><p>${sex(c)} · ${ageText(c)} · ${esc(c.color)} · Poils ${esc(c.coat||'à préciser')}</p><div class="detail-photos">${c.photos.map(p=>`<button type="button" class="photo-zoom" data-photo="${esc(c.largePhotos?.[c.photos.indexOf(p)]||p)}" aria-label="Agrandir la photo ${c.photos.indexOf(p)+1} de ${esc(c.name)}"><img src="${esc(p)}" alt="Photo de ${esc(c.name)}"></button>`).join('')||'<div class="placeholder">Photo à venir</div>'}</div><p class="caption">${esc(c.description||'Présentation à venir.')}</p>${c.status==='adoptable'?'<p class="note">Les rencontres au refuge se font sur rendez-vous. Contactez l’association pour connaître les disponibilités.</p><a class="button" href="https://ecole-du-chat-phoceenne.org/" target="_blank" rel="noopener">Contacter le refuge sur le site actuel ↗</a>':''}`;dialog.showModal();document.querySelectorAll(".photo-zoom").forEach(button=>button.onclick=()=>{const image=document.querySelector("#large-photo");image.onload=()=>{image.style.width=Math.min(image.naturalWidth,1200)+"px";image.style.height="auto"};image.src=button.dataset.photo;image.alt="Photo agrandie de "+c.name;document.querySelector("#photo-dialog").showModal()})}
document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
// Une semaine commence le lundi, selon la date à Marseille.
function featuredCat(population,now=new Date()){
 const eligible=population.filter(c=>c.status==='adoptable'&&c.photos?.length).sort((a,b)=>Number(a.id)-Number(b.id)||String(a.name).localeCompare(String(b.name),'fr'));
 if(!eligible.length)return null;
 const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Paris',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(now);
 const part=type=>Number(parts.find(p=>p.type===type).value);
 const day=Date.UTC(part('year'),part('month')-1,part('day'));
 const week=Math.floor((day-Date.UTC(2026,0,5))/(7*86400000));
 return eligible[((week%eligible.length)+eligible.length)%eligible.length];
}
function newsSharing(){return `<div class="news-sharing"><details class="share-picker"><summary class="button">Partager</summary><div class="share-actions" aria-label="Choisir le mode de partage"><a class="button secondary" data-share="facebook" target="_blank" rel="noopener noreferrer">Facebook ↗</a><a class="button secondary" data-share="whatsapp" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><button type="button" class="button secondary" data-share="instagram">Instagram</button><button type="button" class="button secondary" data-share="copy">Copier le lien</button></div></details><p class="share-feedback" role="status" aria-live="polite"></p></div>`}
function bindNewsSharing(){
 const box=main.querySelector('.news-sharing');if(!box)return;
 const url='https://marinaglvsf.github.io/edc-13.github.io/nouveau-site/#actualite';
 const text='Collectes, kermesses et rendez-vous : découvrez les actualités de l’École du Chat Phocéenne.';
 box.querySelector('[data-share="facebook"]').href='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url);
 box.querySelector('[data-share="whatsapp"]').href='https://wa.me/?text='+encodeURIComponent(text+' '+url);
 const feedback=box.querySelector('.share-feedback');
 async function copy(instagram){try{await navigator.clipboard.writeText(url);feedback.textContent=instagram?'Lien copié. Ouvrez Instagram et collez-le dans un message ou dans le sticker Lien d’une story.':'Lien copié : vous pouvez le coller dans votre message.'}catch(error){feedback.textContent='Lien à copier : '+url}}
 box.querySelector('[data-share="copy"]').onclick=()=>copy(false);
 box.querySelector('[data-share="instagram"]').onclick=()=>copy(true);
}
function supportLinks(){return `<div class="support-links" aria-label="Soutenir directement le refuge"><a class="button secondary" href="https://www.helloasso.com/associations/l-ecole-du-chat-phoceenne" target="_blank" rel="noopener noreferrer">HelloAsso ↗</a><a class="button secondary" href="https://www.amazon.fr/hz/wishlist/ls/112YRKIV53JOE?ref_=wl_share" target="_blank" rel="noopener noreferrer">Liste Amazon ↗</a><a class="button secondary" href="https://www.teaming.net/refugedel-ecoleduchatphoceenne" target="_blank" rel="noopener noreferrer">Teaming ↗</a></div>`}
function home(){const active=cats.filter(c=>c.status==='adoptable');const featured=featuredCat(active);main.innerHTML=`<section class="hero"><div><span class="eyebrow">Un refuge, des histoires, de nouvelles vies</span><h1>Un refuge pour eux,<br><span style="color:var(--orange)">un engagement pour nous</span></h1><p>À Marseille, l’École du Chat Phocéenne protège les chats et accompagne leur rencontre avec une famille aimante.</p></div>${featured?`<div class="hero-photo"><img src="${esc(featured.photos[0])}" alt="${esc(featured.name)} attend une famille"><small>${esc(featured.name)} · Une belle histoire reste à écrire.</small></div>`:''}</section><section class="section home-news"><div class="section-head"><div><span class="eyebrow">La vie du refuge</span><h2>Actualités du refuge</h2></div><a href="#actualite">Toutes les actualités →</a></div><p>Les prochaines nouvelles du refuge, collectes et rendez-vous seront publiés ici.</p>${newsSharing()}</section><section class="support"><div><span class="eyebrow">Vous souhaitez nous donner un petit coup de patte ?</span><h2>Parce que leur bien-être passe aussi par votre soutien.</h2><p>Nourriture, soins, matériel, bénévolat, dons… chaque aide nous est précieuse.</p></div><div class="support-access"><a class="button" href="#association">Comment nous aider</a>${supportLinks()}</div></section>`;bindCards();bindNewsSharing()}
function listing(adopted){const population=cats.filter(c=>c.status===(adopted?'adopté':'adoptable'));const choices=field=>[...new Set(population.map(c=>c[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr')).map(v=>`<option value="${esc(v)}">${esc(field==='coat'?'Poils '+v:v)}</option>`).join('');main.innerHTML=`<span class="eyebrow">${adopted?'Les belles histoires du refuge':'Votre prochaine rencontre'}</span><h1>${adopted?'Ils ont trouvé leur famille de cœur.':'Adopter, c’est changer deux vies.'}</h1><p>${adopted?'Découvrez les chats qui ont trouvé un foyer.':'Découvrez nos chats et ouvrez leur fiche pour faire connaissance.'}</p><form class="filters"><label>Pelage<select id="coat"><option value="">Tous les pelages</option>${choices("coat")}</select></label><label>Couleur<select id="color"><option value="">Toutes les couleurs</option>${choices("color")}</select></label><label>Sexe<select id="sex"><option value="">Tous</option><option value="F">Femelle</option><option value="M">Mâle</option></select></label><button class="reset" type="reset">Réinitialiser</button></form><p class="results" aria-live="polite"></p><div class="grid" id="results"></div>${adopted?'':'<p class="note">Cette liste n’est pas exhaustive. D’autres chats cherchent une famille : venez les rencontrer sur rendez-vous.</p>'}`;
const form=main.querySelector('form');form.onsubmit=e=>e.preventDefault();function update(){const coat=main.querySelector('#coat').value,color=main.querySelector('#color').value,gender=main.querySelector('#sex').value;const filtered=cats.filter(c=>c.status===(adopted?'adopté':'adoptable')&&(!coat||c.coat===coat)&&(!color||c.color===color)&&(!gender||c.sex===gender));if(adopted)filtered.sort((a,b)=>String(b.modified||'').localeCompare(String(a.modified||''))||Number(b.id)-Number(a.id));main.querySelector('.results').textContent=`${filtered.length} chat${filtered.length>1?'s':''} ${adopted?'adopté'+(filtered.length>1?'s':''):'à découvrir'}`;main.querySelector('#results').innerHTML=filtered.map(card).join('')||'<p class="empty">Aucun chat ne correspond à ces critères. Essayez d’élargir votre recherche.</p>';bindCards()}form.oninput=update;form.onreset=()=>setTimeout(update,0);update()}
const editorial={actualite:['La vie du refuge',"Retrouvez les nouvelles du refuge, les collectes et les rendez-vous de l’association."],association:['Une association engagée pour les chats',"L’École du Chat Phocéenne est une association de défense animale et de protection des chats libres."],refuge:['Un lieu de protection et de rencontres',"Le refuge accueille les chats et leur offre soins et attention. Découvrez les lieux et la vie du refuge à travers une visite guidée. Les rencontres en vue d’une adoption se font sur rendez-vous."],aider:['Chaque geste peut changer une vie.',"Vous pouvez soutenir le refuge par un don, du bénévolat, une adoption ou un parrainage."]};
function render(){if(dialog.open)dialog.close();const requested=location.hash.slice(1)||'bienvenue';const key=requested==='visite'?'refuge':requested==='actions'?'association':requested;const selected=sections.find(s=>s[0]===key)||(key==='aider'?['aider','Aider le refuge']:sections[0]);document.querySelector('nav').innerHTML=sections.map(([id,label])=>`<a href="#${id}" ${id===selected[0]?'class="active" aria-current="page"':''}>${esc(label)}</a>`).join('');document.title=selected[1]+' — L’École du Chat Phocéenne';if(selected[0]==='bienvenue')home();else if(selected[0]==='adopter'||selected[0]==='adoptes')listing(selected[0]==='adoptes');else{const [title,text]=editorial[selected[0]];main.innerHTML=`<section class="editorial"><span class="eyebrow">${esc(selected[1])}</span><h1>${title}</h1><p>${text}</p>${selected[0]==='association'?`<section id="soutenir-refuge"><h2>Comment nous aider</h2><p>Pour soutenir le refuge, retrouvez nos actions sur HelloAsso, les articles de notre liste Amazon et notre groupe Teaming.</p>${supportLinks()}</section><section id="nos-actions"><h2>Nos actions</h2><p>Découvrez les actions de l’association en faveur des chats libres et des chats du refuge.</p><p>Les informations sur nos actions seront regroupées ici.</p></section>`:''}<div class="panel"><h2>${selected[0]==='aider'?'Adopter · Donner · Participer':'Le refuge vous ouvre ses portes'}</h2><p>Cette rubrique sera complétée avec le contenu du site actuel. Sa présentation et sa place dans le menu sont conservées dans cette maquette.</p><a class="button" href="https://ecole-du-chat-phoceenne.org/" target="_blank" rel="noopener">Consulter le site actuel ↗</a></div><a href="#adopter">Rencontrer nos chats →</a>${selected[0]==='actualite'?newsSharing():''}</section>`;bindNewsSharing()}window.scrollTo(0,0)}window.addEventListener('hashchange',render);render();

const photoDialog=document.querySelector("#photo-dialog");document.querySelector("#close-photo").onclick=()=>photoDialog.close();photoDialog.addEventListener("click",event=>{if(event.target===photoDialog)photoDialog.close()});

function fitMenu(){
 const menu=document.querySelector('#menu');
 menu.style.setProperty('--menu-font','14px');menu.style.setProperty('--menu-padding','8px');
 const links=[...menu.querySelectorAll('a')];if(!links.length)return;
 const style=getComputedStyle(menu);
 const available=menu.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight);
 const gap=parseFloat(style.columnGap)||0;
 // Réduire d’abord les espaces, puis la typographie, sans retour à la ligne.
 menu.style.setProperty('--menu-padding',innerWidth<600?'2px':'4px');
 for(let size=14;size>=4;size-=0.25){
  menu.style.setProperty('--menu-font',size+'px');
  const total=links.reduce((sum,a)=>sum+a.getBoundingClientRect().width,0)+gap*(links.length-1);
  if(total<=available)break;
 }
}
window.addEventListener('resize',fitMenu);
window.addEventListener('hashchange',fitMenu);
fitMenu();
